// Dart shim placeholder for matrix-rust-sdk via flutter_rust_bridge
// The actual bindings will be generated by flutter_rust_bridge_codegen.

// Dart shim for the native Matrix bridge.
//
// The real bindings will be generated by `flutter_rust_bridge_codegen` as
// `bridge_generated.dart`. This shim adapts those generated functions into a
// small, idiomatic Dart API used by the app.

import 'dart:async';

// TODO: After running flutter_rust_bridge_codegen this import will exist.
// import 'bridge_generated.dart' as bridge;

class MatrixRustBridge {
  static final MatrixRustBridge _instance = MatrixRustBridge._internal();
  factory MatrixRustBridge() => _instance;
  MatrixRustBridge._internal();

  // Example public API. Replace bodies with calls into `bridge.*` once
  // codegen is run and `bridge_generated.dart` is available.

  Future<void> init(String homeserver, String dataDir) async {
    // await bridge.init(homeserver, dataDir);
    throw UnimplementedError(
        'Run flutter_rust_bridge_codegen and wire bridge.init');
  }

  /// Returns a map with keys: `userId` and `accessToken`.
  Future<Map<String, dynamic>> login(String user, String password) async {
    // final json = await bridge.login(user, password);
    // return jsonDecode(json) as Map<String, dynamic>;
    throw UnimplementedError(
        'Run flutter_rust_bridge_codegen and wire bridge.login');
  }

  Future<String> createRoom(String otherMxid) async {
    // return await bridge.create_room(otherMxid);
    throw UnimplementedError(
        'Run flutter_rust_bridge_codegen and wire bridge.create_room');
  }

  Future<String> sendMessage(String roomId, String body) async {
    // return await bridge.send_message(roomId, body);
    throw UnimplementedError(
        'Run flutter_rust_bridge_codegen and wire bridge.send_message');
  }

  // Stream of incoming events forwarded from native side. Once FRB is set up
  // you can implement an event callback in Rust that pushes events into Dart
  // using a StreamController here.
  Stream<Map<String, dynamic>> get events async* {
    yield* const Stream.empty();
  }
}
